name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Integration Tests
        runs-on: ubuntu-latest

        env:
          DB_USER: ${{ secrets.DB_USER }}
          DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
          DB_NAME: ${{ secrets.DB_NAME }}
          DB_HOST: ${{ secrets.DB_HOST }}

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: 14
            
            - name: Install dependencies
              run: npm install 

            - name: Display .env file
              run: |
                echo "DB_USER=${DB_USER}" >> .env
                echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
                echo "DB_NAME=${DB_NAME}" >> .env
                echo "DB_HOST=${DB_HOST}" >> .env
                cat .env
                
            - name: Configure MySQL
              run: |
                sudo apt-get update
                sudo apt-get install -y curl  
                sudo apt-get install -y mysql-client
                sudo systemctl start mysql
                sudo systemctl status mysql
                sleep 10
                mysql -u root -p"root" -e "CREATE DATABASE IF NOT EXISTS webapp;"

            # - name: Run Integration tests
            #   run: |
            #     if npm run test:integration; then
            #       echo "Tests passed successfully."
            #     else
            #       echo "Tests failed."
            #       exit 1
            #     fi
            - name: Run Integration tests
              run : npm run test:integration || true