name: Integration Tests

on:
  pull_request:
    branches:
      - main

jobs:
    build:
        name: Integration Tests
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup node
              uses: actions/setup-node@v2
              with:
                node-version: '14'
            
            - name: Install dependencies
              run: npm install

            - name: Configure MySQL
              run: |
                sudo apt-get update
                sudo apt-get install -y mysql-server
                sudo service mysql start    

            - name: Display .env file
              env:
                DB_USER: ${{ secrets.DB_USER }}
                DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
                DB_NAME: ${{ secrets.DB_NAME }}
              run: |
                echo "DB_USER=root" >> .env
                echo "DB_PASSWORD=root" >> .env
                echo "DB_NAME=webapp" >> .env
                echo "PORT=3306" >> .env
                echo "DB_HOST=127.0.0.1" >> .env
                cat .env

            - name: Run Integration tests
              run: npm run test:integration

            - name: Move to Next Step
              run: exit 0

            