name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-status-check:
    name: Packer Status Check
    runs-on: ubuntu-latest

    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PUBSUB_TOPIC: ${{ secrets.PUBSUB_TOPIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: |
          pwd
          ls -l
        shell: bash

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Create ZIP Archive
        run: zip -r webapp.zip . -x ".git/*" ".gitignore" ".github/*"
        
      - name: Print Contents of Directory
        run: ls -l   
  
      - name: List contents of webapp.zip
        run: unzip -l ./webapp.zip  

      - name: Display .env file
        run: |
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env
          echo "PROJECT_ID=${PROJECT_ID}" >> .env
          echo "PUBSUB_TOPIC=${PUBSUB_TOPIC}" >> .env
          cat .env

      - name: Setup node
        uses: actions/setup-node@v2
        with:
           node-version: 14
        
      - name: Install dependencies
        run: npm install 

      - name: Configure MySQL
        run: |
            sudo apt-get update
            sudo apt-get install -y curl
            sudo systemctl start mysql
            sudo systemctl status mysql
            sleep 10
            mysql -u root -p"root" -e "CREATE DATABASE webapp;"
            
      - name: Run Integration tests
        run: |
          if npm run test:integration; then
            echo "Tests passed successfully."
          else
            echo "Tests failed."
            exit 1
          fi

      - name: Initialize Packer
        run: packer init -upgrade gcp-centos.pkr.hcl || exit 1
        working-directory: packer
        
      - name: Format Packer template
        run: packer fmt -check -diff gcp-centos.pkr.hcl 
        working-directory: packer
  
      - name: Validate Packer template
        run: packer validate gcp-centos.pkr.hcl   
        working-directory: packer 
        
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info 

      # - name: Build AMI with Packer
      #   run: packer build gcp-centos.pkr.hcl
      #   working-directory: packer

      - name: Get Machine Image ID and save it to Github env
        run: |
          echo IMAGE_ID=webappami-20240403090351 >> $GITHUB_ENV
          # echo IMAGE_ID=$(jq -r '.builds[0].artifact_id' ./packer/manifest.json | cut -d':' -f2) >> $GITHUB_ENV
        shell: bash

      - name: Get terraform output
        run: |
          echo INSTANCE_TEMPLATE_LINK=$(terraform output -raw instance_template_self_link) 
          echo INSTANCE_GROUP_MANAGER_LINK=$(terraform output -raw instance_group_manager_link) 
        shell: bash

      - name: Create New Instance Template Version
        run: |
          INSTANCE_NAME="webapp-instance-$(date +%s)"
          IMAGE_ID=${{ env.IMAGE_ID }}
          gcloud compute instances create "${INSTANCE_NAME}" \
          --source-instance-template="${INSTANCE_TEMPLATE_LINK}" \
          --image="${IMAGE_ID}" \
          --image-project="${{ secrets.PROJECT_ID }}" \
          --zone="us-east1-b"
          NEW_INSTANCE_TEMPLATE=$(gcloud compute instance-templates create-from-instance "${INSTANCE_NAME}" \
          --instance-template-name="webapp-template-$(date +%s)" \
          --instance-template-project="${{ secrets.PROJECT_ID }}" \
          --format='value(selfLink)')
          echo $NEW_INSTANCE_TEMPLATE
          gcloud compute instance-templates delete "${INSTANCE_NAME}" --quiet
        shell: bash

      - name: Configure Managed Instance Group
        run: |
          gcloud compute instance-groups managed set-instance-template "${INSTANCE_GROUP_MANAGER_LINK}" \
          --template "${NEW_INSTANCE_TEMPLATE}" \
          --region="us-east1" 
        shell: bash
          

      - name: Start Rolling Update
        run: |
          gcloud compute instance-groups managed rolling-action start-update "${INSTANCE_GROUP_MANAGER_LINK}" \
          --region="us-east1" \
          --max-unavailable "0" \
          --min-ready "2" \
        shell: bash


      - name: Monitor Update Progress
        run: |
          STATUS="ROLLING_OUT"
          while [[ $STATUS == "ROLLING_OUT" ]]
           do
            STATUS=$(gcloud compute instance-groups managed describe "${INSTANCE_GROUP_MANAGER_LINK}" \
            --region="us-east1" \
            --format='value(status)' )
            echo "Current status: $STATUS"
            sleep 10
          done

          if [[ $STATUS == "ROLLED_OUT" ]]
           then
            exit 0
          else
            exit 1
          fi
        shell: bash
