name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-status-check:
    name: Packer Status Check
    runs-on: ubuntu-latest

    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PUBSUB_TOPIC: ${{ secrets.PUBSUB_TOPIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: |
          pwd
          ls -l
        shell: bash

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Create ZIP Archive
        run: zip -r webapp.zip . -x ".git/*" ".gitignore" ".github/*"
        
      - name: Print Contents of Directory
        run: ls -l   
  
      - name: List contents of webapp.zip
        run: unzip -l ./webapp.zip  

      - name: Display .env file
        run: |
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env
          echo "PROJECT_ID=${PROJECT_ID}" >> .env
          echo "PUBSUB_TOPIC=${PUBSUB_TOPIC}" >> .env
          cat .env

      - name: Setup node
        uses: actions/setup-node@v2
        with:
           node-version: 14
        
      - name: Install dependencies
        run: npm install 

      - name: Configure MySQL
        run: |
            sudo apt-get update
            sudo apt-get install -y curl
            sudo systemctl start mysql
            sudo systemctl status mysql
            sleep 10
            mysql -u root -p"root" -e "CREATE DATABASE webapp;"
            
      - name: Run Integration tests
        run: |
          if npm run test:integration; then
            echo "Tests passed successfully."
          else
            echo "Tests failed."
            exit 1
          fi

      - name: Initialize Packer
        run: packer init -upgrade gcp-centos.pkr.hcl || exit 1
        working-directory: packer
        
      - name: Format Packer template
        run: packer fmt -check -diff gcp-centos.pkr.hcl 
        working-directory: packer
  
      - name: Validate Packer template
        run: packer validate gcp-centos.pkr.hcl   
        working-directory: packer 
        
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info 

      # - name: Build AMI with Packer
      #   run: packer build gcp-centos.pkr.hcl
      #   working-directory: packer

      - name: Get Machine Image ID and save it to Github env
        run: |
          echo IMAGE_ID=webappami-20240410103802 >> $GITHUB_ENV
          # echo IMAGE_ID=$(jq -r '.builds[0].artifact_id' ./packer/manifest.json | cut -d':' -f2) >> $GITHUB_ENV
        shell: bash
 
      - name: Create New Instance Template Version
        run: |
          INSTANCE_TEMPLATE=$(gcloud compute instance-templates list --format="value(NAME)")
          INSTANCE_TEMPLATE_SELF_LINK=$(gcloud compute instance-templates describe "${INSTANCE_TEMPLATE}" --region="us-central1" --format="value(selfLink)")
          INSTANCE_GROUP_MANAGER_INSTANCE_GROUP=$(gcloud compute instance-groups list --format="value(NAME)")
          echo "INSTANCE_TEMPLATE=$INSTANCE_TEMPLATE" >> $GITHUB_ENV
          echo "INSTANCE_TEMPLATE_SELF_LINK=$INSTANCE_TEMPLATE_SELF_LINK" >> $GITHUB_ENV
          echo "INSTANCE_GROUP_MANAGER_INSTANCE_GROUP=$INSTANCE_GROUP_MANAGER_INSTANCE_GROUP" >> $GITHUB_ENV
          INSTANCE_NAME="webapp-instance-${{ github.sha }}"
          echo "INSTANCE_NAME=$INSTANCE_NAME" >> $GITHUB_ENV
          IMAGE_ID=${{ env.IMAGE_ID }}
          gcloud compute instances create "${INSTANCE_NAME}" \
            --source-instance-template="${INSTANCE_TEMPLATE_SELF_LINK}" \
            --image="${IMAGE_ID}" \
            --image-project="${{ secrets.PROJECT_ID }}" \
            --zone=us-central1-a 
          NEW_INSTANCE_TEMPLATE_SELF_LINK=$(gcloud compute instance-templates create "webapp-template-${{ github.sha }}" \
            --source-instance="${INSTANCE_NAME}" \
            --source-instance-zone="us-central1-a" \
            --format='value(selfLink)')
          gcloud compute instances delete "${INSTANCE_NAME}" --zone=us-central1-a --quiet
 
      - name: Update Managed Instance Group
        run: |
          gcloud compute instance-groups managed set-instance-template "${INSTANCE_GROUP_MANAGER_INSTANCE_GROUP}" \
            --template "${NEW_INSTANCE_TEMPLATE_SELF_LINK}" \
            --region=us-central1
 
      - name: Start Rolling Update
        run: |
          gcloud compute instance-groups managed rolling-action start-update "${INSTANCE_GROUP_MANAGER_INSTANCE_GROUP}" \
            --version template="${NEW_INSTANCE_TEMPLATE_SELF_LINK}" \
            --region=us-central1 \
            --max-unavailable "0" \
            --min-ready "2"
     
            - name: Monitor Update
            run: |
              STATUS="ROLLING_OUT"
              while [[ $STATUS == "ROLLING_OUT" ]]
              do
                STATUS=$(gcloud compute instance-groups managed describe "${INSTANCE_GROUP_MANAGER_INSTANCE_GROUP}" \
                  --region=us-central1 \
                  --format='value(status)')
                echo "Instance group is $STATUS"
                sleep 10
              done
         
              if [[ $STATUS == "ROLLED_OUT" ]]
              then
                exit 0
              else
                exit 1
              fi
