name: Packer AMI Build

on:
  push:
    branches:
      - main

jobs:
  build-ami:
    name: Build Packer AMI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Create ZIP Archive
        run: zip -r webapp.zip . -x ".git/*" ".gitignore" ".github/*"

      - name: Display ZIP File Location
        run: |
          echo "ZIP file location: $GITHUB_WORKSPACE/webapp.zip"
          
      - name: Print Contents of Directory
        run: ls -l
      
      - name: List contents of webapp.zip
        run: unzip -l ./webapp.zip
      
      - name: Initialize Packer
        run: packer init -upgrade gcp-centos.pkr.hcl || exit 1
        working-directory: packer

      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info 

      - name: Display .env file
        run: |
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env
          cat .env

      - name: Setup node
        uses: actions/setup-node@v2
        with:
           node-version: 14
        
      - name: Install dependencies
        run: npm install 

      - name: Configure MySQL
        run: |
            sudo apt-get update
            sudo apt-get install -y curl  
            sudo apt-get install -y mysql-client
            sudo systemctl start mysql
            sudo systemctl status mysql
            sleep 10
            mysql -u root -p"root" -e "CREATE DATABASE IF NOT EXISTS webapp;"  
        
      - name: Run Integration tests
        run: |
          if npm run test:integration; then
            echo "Tests passed successfully."
          else
            echo "Tests failed."
            exit 1
          fi

      - name: Build AMI with Packer
        run: packer build gcp-centos.pkr.hcl
        working-directory: packer
