name: Packer Status Check

on:
  pull_request:
    branches:
      - main

jobs:
  packer-status-check:
    name: Packer Status Check
    runs-on: ubuntu-latest

    env:
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_HOST: ${{ secrets.DB_HOST }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
        PUBSUB_TOPIC: ${{ secrets.PUBSUB_TOPIC }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Print Current Directory
        run: |
          pwd
          ls -l
        shell: bash

      - name: Setup Packer
        uses: hashicorp/setup-packer@main
        with:
          version: '1.8.6'

      - name: Create ZIP Archive
        run: zip -r webapp.zip . -x ".git/*" ".gitignore" ".github/*"
        
      - name: Print Contents of Directory
        run: ls -l   
  
      - name: List contents of webapp.zip
        run: unzip -l ./webapp.zip  

      - name: Display .env file
        run: |
          echo "DB_USER=${DB_USER}" >> .env
          echo "DB_PASSWORD=${DB_PASSWORD}" >> .env
          echo "DB_NAME=${DB_NAME}" >> .env
          echo "DB_HOST=${DB_HOST}" >> .env
          echo "PROJECT_ID=${PROJECT_ID}" >> .env
          echo "PUBSUB_TOPIC=${PUBSUB_TOPIC}" >> .env
          cat .env

      - name: Setup node
        uses: actions/setup-node@v2
        with:
           node-version: 14
        
      - name: Install dependencies
        run: npm install 

      - name: Configure MySQL
        run: |
            sudo apt-get update
            sudo apt-get install -y curl
            sudo systemctl start mysql
            sudo systemctl status mysql
            sleep 10
            mysql -u root -p"root" -e "CREATE DATABASE webapp;"
            
      - name: Run Integration tests
        run: |
          if npm run test:integration; then
            echo "Tests passed successfully."
          else
            echo "Tests failed."
            exit 1
          fi

      - name: Initialize Packer
        run: packer init -upgrade gcp-centos.pkr.hcl || exit 1
        working-directory: packer
        
      - name: Format Packer template
        run: packer fmt -check -diff gcp-centos.pkr.hcl 
        working-directory: packer
  
      - name: Validate Packer template
        run: packer validate gcp-centos.pkr.hcl   
        working-directory: packer 
        
      - name: Authenticate with GCP
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}

      - name: Setup Cloud SDK
        uses: google-github-actions/setup-gcloud@v2

      - name: Use gcloud CLI
        run: gcloud info 

      # - name: Build AMI with Packer
      #   run: packer build gcp-centos.pkr.hcl
      #   working-directory: packer

      - name: Get Machine Image ID and save it to Github env
        run: |
          echo IMAGE_ID=webappami-20240403090351 >> $GITHUB_ENV
          # echo IMAGE_ID=$(jq -r '.builds[0].artifact_id' ./packer/manifest.json | cut -d':' -f2) >> $GITHUB_ENV
        shell: bash

      - name: Create New Instance Template Version
        run: |
          gcloud compute instance-templates create new-template \
          --source-instance-template "webapp-instance-template-*" \
          --machine-image=${{ env.IMAGE_ID }} \
          --metadata="${{secrets.MMETADATA_SCRIPT}}" \
          --project ${{ secrets.PROJECT_ID }}

      - name: Configure Managed Instance Group
        run: |
          gcloud compute instance-groups managed set-instance-template web-instance-group-manager \
          --template new-template \
          --zone us-east1-b \
          --project ${{ secrets.PROJECT_ID }}
          
      - name: Start Rolling Update
        run: |
          gcloud compute instance-groups managed rolling-action start-update web-instance-group-manager \
          --version new-template \
          --zone us-east1-b \
          --project ${{ secrets.PROJECT_ID }}

      - name: Monitor Update Progress
        id: monitor_update
        run: |
          status=$(gcloud compute instance-groups managed describe web-instance-group-manager \
            --zone us-east1-b \
            --format='value(instanceGroupStatus.versionStatus[0].status)' \
            --project ${{ secrets.PROJECT_ID }})
          echo "::set-output name=status::$status"

      - name: Wait for Update Completion
        run: |
          while [[ "$(steps.monitor_update.outputs.status)" != "UP_TO_DATE" ]]; do
            sleep 10
            status=$(gcloud compute instance-groups managed describe web-instance-group-manager \
              --zone us-east1-b \
              --format='value(instanceGroupStatus.versionStatus[0].status)' \
              --project ${{ secrets.PROJECT_ID }})
            echo "Current status: $status"
          done